#!/usr/bin/env bash
# Auto-generated by scripts/generate_sample_artifacts.py from sample.yaml.
# Edit sample.yaml and rerun the generator — do not hand-edit this file.
#
# Deploy the Security Triage Agent sample.
#
# Usage:  ./deploy.sh

set -euo pipefail

cd "$(dirname "$0")"

# Resolve which CLI binary to invoke (archastro vs archagent). Order:
#   1. $ARCHASTRO_CLI env override
#   2. Nearest archastro.json / archagent.json walking up from here
#   3. First of archastro / archagent on PATH
#   4. Fallback: archagent
if [[ -n "${ARCHASTRO_CLI:-}" ]]; then
  CLI="$ARCHASTRO_CLI"
else
  CLI=""
  _dir="$PWD"
  while [[ -n "$_dir" && "$_dir" != "/" ]]; do
    if [[ -f "$_dir/archastro.json" ]]; then CLI="archastro"; break; fi
    if [[ -f "$_dir/archagent.json" ]]; then CLI="archagent"; break; fi
    _dir="$(dirname "$_dir")"
  done
  unset _dir
  if [[ -z "$CLI" ]]; then
    if   command -v archastro >/dev/null 2>&1; then CLI="archastro"
    elif command -v archagent >/dev/null 2>&1; then CLI="archagent"
    else CLI="archagent"
    fi
  fi
fi

if [[ ! -f .env ]]; then
  echo "ℹ️  No .env file found. Copy env.example to .env if you need custom values."
else
  # shellcheck disable=SC1091
  source .env
fi

echo "📜 Deploying scripts..."
for script in scripts/*.aascript; do
  name=$(basename "$script" .aascript | tr '_' '-')
  pretty=$(echo "$name" | tr '-' ' ')
  echo "  → $name"
  "$CLI" create scripts \
    --id "$name" \
    --name "$pretty" \
    --file "$script" 2>/dev/null || \
  "$CLI" update scripts "$name" --file "$script"
done

echo "🤖 Deploying agent..."
"$CLI" deploy agent agent.yaml

echo ""
echo "✅ Security Triage Agent deployed."
echo ""
echo "Inspect the agent:"
echo "  $CLI describe agent security-triage-agent"
