"""
Pure rendering of the generated artifacts. Functions in here have no
filesystem side effects beyond the read in render_aaignore — the
generate module handles writes + drift comparison.
"""
from __future__ import annotations

import json
import pathlib
from typing import Any

from .paths import AAIGNORE_SKIP, MANIFEST_SCHEMA_VERSION


def render_aaignore(sample_dir: pathlib.Path) -> str:
    """
    Produce the sample's .aaignore. Every top-level entry in the sample
    dir is listed so `archastro deploy configs` treats the sample as
    install-authoritative and skips it entirely — the DSL executor
    handles every file inside.
    """
    entries: list[str] = []
    for child in sorted(sample_dir.iterdir()):
        if child.name in AAIGNORE_SKIP:
            continue
        entries.append(f"{child.name}/" if child.is_dir() else child.name)
    header = (
        "# Auto-generated by `uv run scripts/sample_tool.py generate` — do not edit.\n"
        "#\n"
        "# This sample is installed via `archastro install agentsample <slug>`,\n"
        "# which reads sample.yaml's `steps:` block and runs the DSL executor.\n"
        "# `archastro deploy configs` should skip every file inside this\n"
        "# directory.\n"
    )
    return header + "\n".join(entries) + "\n"


def render_manifest(samples: list[dict[str, Any]]) -> str:
    """
    Build samples.json. The CLI + portal read this file directly to
    populate their sample-selection menus — one network round trip for
    the whole catalog.

    Deterministic: no `generated_at` timestamp so `--check` is stable.
    Per-version release dates come from the GitHub Release timestamp.
    """
    manifest = {
        "$schema_version": MANIFEST_SCHEMA_VERSION,
        "samples": [
            {
                "slug": s["slug"],
                "name": s["name"],
                "tagline": s["tagline"],
                "current_version": s["version"],
                "min_cli_version": s["min_cli_version"],
            }
            for s in samples
        ],
    }
    return json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"
